- name: stop oracle
  service: name=oracle state=stopped
  with_items: "{{oracle_latest_patches}}"
  when: ansible_connection != 'docker'

- name: create database
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ora_user_env}}"
  command: "{{ ora_user_env.ORACLE_HOME }}/bin/dbca -silent -createDatabase -templateName General_Purpose.dbc -sid {{oracle_db_name}} -gdbName {{oracle_db_name}} -datafileDestination {{ ora_user_env.ORACLE_BASE }}/oradata -responseFile {{oracle_tmp}}/dbca.rsp -syspassword {{oracle_db_syspass}} -systempassword {{oracle_db_syspass}} -dbsnmppassword {{oracle_db_syspass}}"
  args:
    creates: "{{ ora_user_env.ORACLE_BASE }}/oradata/{{oracle_db_name}}"
