---
# Install latest patch for Oracle
- name: download oracle patch
  get_url: url={{ oracle_installer_uri }}/{{ oracle_latest_patch }} dest={{ oracle_tmp }}/{{ oracle_latest_patch }} checksum={{oracle_latest_patch_checksum}}

- name: unzip patch
  unarchive:
    src: "{{ oracle_tmp }}/{{ oracle_latest_patch }}"
    dest: "{{ oracle_tmp }}"
    copy: no
    creates: "{{ oracle_tmp }}/{{oracle_patch_num}}"
    owner: "{{ oracle_user }}"

- name: download oracle opatch
  get_url: url={{ oracle_installer_uri }}/{{ oracle_opatch }} dest={{ oracle_tmp }}/{{ oracle_opatch }} checksum={{oracle_opatch_checksum}}

- name: unzip opatch
  unarchive:
    src: "{{ oracle_tmp }}/{{ oracle_opatch }}"
    dest: "{{ oracle_tmp }}"
    copy: no
    creates: "{{ oracle_tmp }}/OPatch"
    owner: "{{ oracle_user }}"

- name: generate response response file
  shell: "echo ''| {{ oracle_tmp }}/OPatch/ocm/bin/emocmrsp -output ./ocm.rsp foo bar"
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  args:
      chdir: "{{ ora_user_env.ORACLE_HOME }}"
      creates: "{{ ora_user_env.ORACLE_HOME }}/ocm.rsp"
  register: gen_rsp_file

- name: Stop oracle service
  service: name=oracle state=stopped
  when: gen_rsp_file | success

- name: apply latest patch rdbms
  command: "{{ oracle_tmp }}/OPatch/opatch apply -silent -ocmrf {{ ora_user_env.ORACLE_HOME }}/ocm.rsp"
  environment: "{{ ora_user_env }}"
  become_user: "{{ oracle_user }}"
  args:
      chdir: "{{ oracle_tmp }}/{{ oracle_patch_num }}"
  when: gen_rsp_file | success
