---
# Install latest patch for Oracle

- name: get opatch version
  command: "{{ora_user_env.ORACLE_HOME}}/OPatch/opatch version"
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  register: opatch_version

- name: unzip opatch
  unarchive:
    src: "{{ oracle_installer_uri }}/{{ oracle_opatch }}"
    dest: "{{ ora_user_env.ORACLE_HOME }}"
    copy: no
    owner: "{{ oracle_user }}"
  when: opatch_version.stdout.find(oracle_opatch_version) == -1

- name: get oracle support site access
  shell: ping -c 3 support.oracle.com | grep -q '100% packet loss'
  args:
      creates: "{{ ora_user_env.ORACLE_HOME }}/ocm.rsp"
  register: no_support_access
  ignore_errors: yes

  #failed_when: support_access.rc not in [0, 1]

- name: generate response file
  shell: echo {{no_support_access|success | ternary('NONE','')}}| {{ ora_user_env.ORACLE_HOME }}/OPatch/ocm/bin/emocmrsp -output {{ ora_user_env.ORACLE_HOME }}/ocm.rsp -repeater NONE -no_banner foo bar
  become: yes
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  args:
      chdir: "{{ ora_user_env.ORACLE_HOME }}"
      creates: "{{ ora_user_env.ORACLE_HOME }}/ocm.rsp"

- name: get patch list
  shell: "{{ ora_user_env.ORACLE_HOME }}/OPatch/opatch lsinventory |egrep '[0-9]{8,}'"
  environment: "{{ ora_user_env }}"
  become: yes
  become_user: "{{ oracle_user }}"
  register: patch_list
  failed_when: patch_list.rc > 1

- block:
    - name: stop oracle
      service: name=oracle state=stopped
      with_items: "{{oracle_latest_patches}}"

    - name: create patches folders
      file: name={{ oracle_tmp }}/{{ item.number }} state=directory owner={{ oracle_user }}
      with_items: "{{oracle_latest_patches}}"

    - name: unzip patches
      unarchive:
        src: "{{ oracle_installer_uri }}/{{ item.file_name }}"
        dest: "{{ oracle_tmp }}/{{ item.number }}"
        copy: no
        creates: "{{ oracle_tmp }}/{{ item.number }}/{{ item.number }}"
        owner: "{{ oracle_user }}"
      with_items: "{{oracle_latest_patches}}"

    - name: apply latest patch rdbms
      command: "{{ ora_user_env.ORACLE_HOME }}/OPatch/opatch {{item.apply | default('apply')}} -silent -ocmrf {{ ora_user_env.ORACLE_HOME }}/ocm.rsp {{ oracle_tmp }}/{{ item.number }}/{{ item.number }}"
      environment: "{{ ora_user_env }}"
      become: yes
      become_user: "{{ oracle_user }}"
      with_items: "{{oracle_latest_patches}}"
  when: patch_list.stdout.find(item.number) == -1

- name: register and start up the oracle service
  service: name=oracle state=started enabled=yes
